version: "3.7"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    environment:
      - SYNAPSE_SERVER_NAME=matrix.koyeb.app
      - SYNAPSE_REPORT_STATS=yes
    ports:
      - "8008:8008"
    volumes:
      - synapse-data:/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 400M

  element:
    image: vectorim/element-web:latest
    environment:
      - REACT_APP_DEFAULT_SERVER_URL=https://matrix.koyeb.app
    ports:
      - "80:80"
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M

volumes:
  synapse-data:
