server_name: matrix.koyeb.app
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    type: http
    tls: false
    resources:
      - names: [client, federation]
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
report_stats: yes
